//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cardiovascularnote
    {
        public string auscultationSite { get; set; }
        public string capillaryRefillLLM { get; set; }
        public string capillaryRefillLRM { get; set; }
        public string cardiacPressureIntensity { get; set; }
        public string cardiacPressureRhythm { get; set; }
        public byte[] diastolicPhase { get; set; }
        public byte[] edemaAnkle { get; set; }
        public byte[] edemaGeneralized { get; set; }
        public byte[] edemaLowerMembers { get; set; }
        public byte[] fourthNoise { get; set; }
        public string gastrointestinalSemiology { get; set; }
        public byte[] murmurs { get; set; }
        public byte[] neckRadiation { get; set; }
        public string otherSymptoms { get; set; }
        public string pedalPulsesL { get; set; }
        public string pedalPulsesR { get; set; }
        public string pulsesLLM { get; set; }
        public string pulsesLRM { get; set; }
        public string radialPulsesL { get; set; }
        public string radialPulsesR { get; set; }
        public byte[] systolicPhase { get; set; }
        public byte[] thirdNoise { get; set; }
        public byte[] trophicChanges { get; set; }
        public string vesicularWhisperL { get; set; }
        public string vesicularWhisperR { get; set; }
        public long id { get; set; }
    
        public virtual note note { get; set; }
        public virtual cardiovascularnote_cardiovascularsymptoms cardiovascularnote_cardiovascularsymptoms { get; set; }
    }
}
