//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cardiovascularnote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cardiovascularnote()
        {
            this.cardiovascularnote_cardiovascularsymptoms = new HashSet<cardiovascularnote_cardiovascularsymptoms>();
        }
    
        public long id { get; set; }
        public Nullable<long> note_id { get; set; }
        public string auscultationSite { get; set; }
        public string capillaryRefillLLM { get; set; }
        public string capillaryRefillLRM { get; set; }
        public string cardiacPressureIntensity { get; set; }
        public string cardiacPressureRhythm { get; set; }
        public bool diastolicPhase { get; set; }
        public bool edemaAnkle { get; set; }
        public bool edemaGeneralized { get; set; }
        public bool edemaLowerMembers { get; set; }
        public bool fourthNoise { get; set; }
        public string gastrointestinalSemiology { get; set; }
        public bool murmurs { get; set; }
        public bool neckRadiation { get; set; }
        public string otherSymptoms { get; set; }
        public string pedalPulsesL { get; set; }
        public string pedalPulsesR { get; set; }
        public string pulsesLLM { get; set; }
        public string pulsesLRM { get; set; }
        public string radialPulsesL { get; set; }
        public string radialPulsesR { get; set; }
        public bool systolicPhase { get; set; }
        public bool thirdNoise { get; set; }
        public bool trophicChanges { get; set; }
        public string vesicularWhisperL { get; set; }
        public string vesicularWhisperR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cardiovascularnote_cardiovascularsymptoms> cardiovascularnote_cardiovascularsymptoms { get; set; }
        public virtual note note { get; set; }
    }
}
