//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public string parentCompany { get; set; }
        public string labName { get; set; }
        public long ruc { get; set; }
    
        public virtual user user { get; set; }
    }
}
