//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medicine()
        {
            this.notemedicines = new HashSet<notemedicine>();
        }
    
        public long id { get; set; }
        public string concentration { get; set; }
        public bool deleted { get; set; }
        public string form { get; set; }
        public Nullable<long> fractions { get; set; }
        public string healthRegistration { get; set; }
        public string name { get; set; }
        public string owner { get; set; }
        public string presentation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notemedicine> notemedicines { get; set; }
    }
}
