//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class noteexam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public noteexam()
        {
            this.note_noteexam = new HashSet<note_noteexam>();
            this.noteexam_upload = new HashSet<noteexam_upload>();
        }
    
        public long id { get; set; }
        public bool deleted { get; set; }
        public string observation { get; set; }
        public string specification { get; set; }
        public string status { get; set; }
        public long exam_id { get; set; }
        public long note_id { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual note note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<note_noteexam> note_noteexam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<noteexam_upload> noteexam_upload { get; set; }
    }
}
