//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class notediagnosi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public notediagnosi()
        {
            this.notes = new HashSet<note>();
        }
    
        public long id { get; set; }
        public byte[] deleted { get; set; }
        public string diagnosisType { get; set; }
        public Nullable<long> diagnosis_id { get; set; }
        public Nullable<long> note_id { get; set; }
    
        public virtual diagnosi diagnosi { get; set; }
        public virtual note note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<note> notes { get; set; }
    }
}
