//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class notereferral
    {
        public long id { get; set; }
        public bool deleted { get; set; }
        public string reason { get; set; }
        public string specialty { get; set; }
        public Nullable<long> note_id { get; set; }
    
        public virtual note note { get; set; }
    }
}
