//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class notemedicine
    {
        public long id { get; set; }
        public bool deleted { get; set; }
        public Nullable<long> durationTime { get; set; }
        public string durationUnit { get; set; }
        public Nullable<long> frequencyTime { get; set; }
        public string frequencyUnit { get; set; }
        public string indication { get; set; }
        public Nullable<long> medicine_id { get; set; }
        public Nullable<long> note_id { get; set; }
    
        public virtual medicine medicine { get; set; }
        public virtual note note { get; set; }
    }
}
