//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class nurse
    {
        public string medicRegistration { get; set; }
        public long id { get; set; }
    
        public virtual user user { get; set; }
        public virtual nurse_specialties nurse_specialties { get; set; }
    }
}
