//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_medic_permission
    {
        public long patient_id { get; set; }
        public long medic_id { get; set; }
        public bool permission { get; set; }
        public bool is_future_request_blocked { get; set; }
    
        public virtual medic medic { get; set; }
        public virtual patient patient { get; set; }
    }
}
