//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.notes = new HashSet<note>();
            this.patient_allergies = new HashSet<patient_allergies>();
            this.patient_fatherbackgrounds = new HashSet<patient_fatherbackgrounds>();
            this.patient_medicines = new HashSet<patient_medicines>();
            this.patient_motherbackgrounds = new HashSet<patient_motherbackgrounds>();
            this.patient_personalbackgrounds = new HashSet<patient_personalbackgrounds>();
            this.triages = new HashSet<triage>();
        }
    
        public long id { get; set; }
        public string alcohol { get; set; }
        public string bloodType { get; set; }
        public Nullable<long> cigaretteNumber { get; set; }
        public string createdTicket { get; set; }
        public Nullable<long> dormNumber { get; set; }
        public string educationalAttainment { get; set; }
        public bool electricity { get; set; }
        public Nullable<long> fractureNumber { get; set; }
        public string fruitsVegetables { get; set; }
        public string highGlucose { get; set; }
        public string homeMaterial { get; set; }
        public string homeOwnership { get; set; }
        public string homeType { get; set; }
        public string occupation { get; set; }
        public string otherAllergies { get; set; }
        public string otherFatherBackground { get; set; }
        public string otherMedicines { get; set; }
        public string otherMotherBackground { get; set; }
        public string otherPersonalBackground { get; set; }
        public string physicalActivity { get; set; }
        public Nullable<long> residentNumber { get; set; }
        public bool sewage { get; set; }
        public bool water { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<note> notes { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient_allergies> patient_allergies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient_fatherbackgrounds> patient_fatherbackgrounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient_medicines> patient_medicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient_motherbackgrounds> patient_motherbackgrounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient_personalbackgrounds> patient_personalbackgrounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<triage> triages { get; set; }
    }
}
