//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.notes = new HashSet<note>();
            this.patients = new HashSet<patient>();
        }
    
        public long id { get; set; }
        public string address { get; set; }
        public System.DateTime birthday { get; set; }
        public string cellphone { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public bool deletable { get; set; }
        public bool deleted { get; set; }
        public string documentNumber { get; set; }
        public string documentType { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string lastNameFather { get; set; }
        public string lastNameMother { get; set; }
        public string maritalStatus { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public bool organDonor { get; set; }
        public string password_hash { get; set; }
        public string phone { get; set; }
        public string sex { get; set; }
        public System.DateTime since { get; set; }
        public long country_id { get; set; }
        public Nullable<long> district_id { get; set; }
        public Nullable<long> role_id { get; set; }
        public Nullable<long> department_id { get; set; }
        public Nullable<long> province_id { get; set; }
    
        public virtual country country { get; set; }
        public virtual department department { get; set; }
        public virtual district district { get; set; }
        public virtual district district1 { get; set; }
        public virtual medic medic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<note> notes { get; set; }
        public virtual nurse nurse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient> patients { get; set; }
        public virtual role role { get; set; }
    }
}
